### ISSUE TITLE
Can't centre images in "Image Mode"

### ISSUE THREAD

**Issue by oparoz** [s-yadav/iv-viewer#5]
### Test 1
1. Create a container with both width and height set at 100%
2. Append an `img` containing a small image
3. Apply ImageViewer to the image (Image Mode)

The image sits top left instead of being centred
### Test 2
1. Create the same setup as above
2. Set both width and height of `iv-container` at 100% in hope it will keep all the sub-divs centred

Images are now centred, but they're stretched to fill the screen

**Comment by oparoz** [comment]
Same problem in container mode

**Comment by s-yadav** [comment]
For **Test 1**,
ImageViewer in image mode does not care about its container, instead, it wraps image inside an image-viewer container. That must be disturbing your centered aligned image. Instead of positioning image you can position .iv-container, something like

``` css
  .iv-container{
    position : absolute;
    transform : translate(-50%,-50%);
    top : 50%;
    left : 50%; 
  }
```

For **Test 2** it shouldn't happen, I will try to reproduce it though. It will be helpful if you can share any jsfiddle or codepen
