### ISSUE TITLE
.iv-snap-view z-order

### ISSUE THREAD

**Issue by atomGit** [s-yadav/iv-viewer#68]
seems like the zoom/snap view box should remain on top of the main image

i added this style...

```css
.iv-container > .iv-snap-view {
    z-index: 9999;  /* keep zoom box on top of image */
}
```
